CREATE TABLE  N30Reports (
   	amend integer null,
	amendedTracingNumber integer null,
	amendmentDesc text null,
	attachmentUrl text null,
	capital integer null,
	code integer null,
	companyName text null,
	monthDesc text null,
	monthIncome integer null,
	period integer null,
	publishTime integer null,
	rpMonth integer null,
	rpYear integer null,
	sendTime integer null,
	smMonth integer null,
	smYear integer null,
	symbol text null,
	tracingNumber integer null,
	type integer null,
    url integer null,
    yearDesc integer null,
    yearIncome integer null
)