CREATE TABLE  Letters (
   	tracingNumber integer null,
	symbol text null,
	companyName text null,
	underSupervision integer null,
	title text null,
	code text null,
	sendTime text null,
	publishTime text null,
	hasHtml integer null,
	url text null,
	hasExcel integer null,
	hasPdf integer null,
	hasXbrl integer null,
	hasAttachment integer null,
	attachmentUrl text null,
	pdfUrl text null,
	excelUrl text null,
	xbrlUrl text null,
	tedanUrl text null,

    period integer null,
    rpMonth integer null,
    rpYear integer null,
    audited integer null,
    consolidated integer null
)